config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :users, only: [:show, :edit, :update, :destroy]

  concern :reviews do |options|
    resources :reviews, options
  end


  resources :movies, only: [:index, :show, :create, :destroy] do
    concerns :reviews, only: [:create]
    resources :actors, module: :movies
  end
  resources :actors, only: [:index, :show, :delete] do
    concerns :reviews, only: [:create]
  end

  resources :authors, only: [:index, :show] do
   concerns :reviews, only: [:new, :create]
  end

end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id          :integer          not null, primary key
#  age         :integer
#  profession  :string
#  biography   :text
#  nationality :string
#  user_id     :integer
#  image_id    :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  first_name  :string
#  last_name   :string
#
# Indexes
#
#  index_actors_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_477d25671f  (user_id => users.id)
#

class Actor < ApplicationRecord
  mount_uploader :image_id, PhotoUploader
  belongs_to :user
  has_many :filmings, dependent: :destroy
  has_many :movies, through: :filmings
  has_many :reviews, as: :reviewable, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filming.rb
# == Schema Information
#
# Table name: filmings
#
#  id         :integer          not null, primary key
#  actor_id   :integer
#  movie_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_filmings_on_actor_id  (actor_id)
#  index_filmings_on_movie_id  (movie_id)
#
# Foreign Keys
#
#  fk_rails_756668361e  (actor_id => actors.id)
#  fk_rails_ff2405190d  (movie_id => movies.id)
#

class Filming < ApplicationRecord
  belongs_to :actor
  belongs_to :movie
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  date        :date
#  description :text
#  picture     :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  available   :boolean
#  category    :string
#
# Indexes
#
#  index_movies_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_2c7f519372  (user_id => users.id)
#

class Movie < ApplicationRecord
  mount_uploader :picture, PhotoUploader
  belongs_to :user, optional: true
  has_many :filmings, dependent: :destroy
  has_many :actors, through: :filmings
  has_many :reviews, as: :reviewable, dependent: :destroy

  validates :title,
            presence: true,
            uniqueness: true,
            length: { minimum: 2 }
  validates :description, presence: true,length: { minimum: 10, maximum: 2000 }
  validates :picture, presence: true
  validates :available, presence: true

  accepts_nested_attributes_for :actors
  validates_associated :actors

  scope :available, -> { where(available: :true) }

end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  reviewable_type :string
#  reviewable_id   :integer
#
# Indexes
#
#  index_reviews_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_74a66bd6c5  (user_id => users.id)
#

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :reviewable, polymorphic: true

  validates :body, presence: true, length: { minimum: 3 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  username               :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :actors
  has_many :movies
  has_many :reviews

 validates :username,
            :presence => true,
            :uniqueness => {:case_sensitive => false},
            length: { minimum: 2 }

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all.order(:last_name)
  end

  def show
    @actor = Actor.includes(:movies).find(params[:id])

    @last_reviews = @actor.reviews.last(9)
    @reviews = @last_reviews.select do |review|
      review.persisted?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :destroy]

  def index
    @movies = Movie.all
    @movies_available = Movie.available
    @movie = Movie.new
    @movie.actors.new
  end

  def show
    @last_reviews = @movie.reviews.last(9)
    @reviews = @last_reviews.select do |review|
      review.persisted?
    end
  end

  def create
    @movie = current_user.movies.new(movie_params)
    @movie.actors.first.user_id = current_user.id
    @movie.user = current_user

    if params[:movie][:actors_attributes].present?
      @movie.actors.first.profession = "Acteur"
    end

    if @movie.save
      redirect_to movies_path, notice: "'#{@movie.title}' posté!"
    else
      render :index, alert: "oops, remplissez les cases manquantes"
    end
  end

  def destroy
    if @movie.user = current_user
      @movie.destroy
      redirect_to movies_path, notice: "votre film a été supprimé!"
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :description, :date, :picture, :picture_cache, :available, :category, actors_attributes: [:first_name, :last_name, :image_id, :image_id_cache])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    if(params.has_key?(:movie_id))
      @reviewable = Movie.find(params[:movie_id])
      @review = @reviewable.reviews.new(reviews_params)
      @review.user = current_user

      if @review.save
      respond_to do |format|
        format.html { redirect_to @reviewable }
        format.js
      end
      else
        respond_to do |format|
          format.html { render 'movies/show' }
          format.js
        end
      end

    elsif(params.has_key?(:actor_id))
      @reviewable = Actor.find(params[:actor_id])
      @review = @reviewable.reviews.new(reviews_params)
      @review.user = current_user

      if @review.save
      respond_to do |format|
        format.html { redirect_to @reviewable }
        format.js
      end
      else
        respond_to do |format|
          format.html { render 'actors/show' }
          format.js
        end
      end
    end
  end

    private

    def reviews_params
      params.require(:review).permit(:body)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/index.html.erb
<div class="wrapper-actors">
  <div class="container">
    <div class="row">
      <% if @actors.any? %>
        <% @actors.each do |actor, index| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= link_to actor_path(actor) do %>
              <div class="card-actor">
                <div class="card-body">
                  <div class="card-picture" id="actor_<%= index%>" style="background-image:url('<%= actor.image_id? ? cloudinary_url(actor.image_id, height: 300, width: 400, crop: :fill, gravity: :face) : image_path('background.jpg') %>')">
                      <div class="card-hover">
                        <% if actor.first_name? && actor.last_name? %>
                          <p><%= time_ago_in_words(actor.created_at) %></p><br>
                          <p><%= pluralize actor.reviews.size, "review" %></p>
                      </div>
                    </div>
                    <div class="card-infos">
                      <ul class="list-inline">
                        <li>
                          <h4><%= actor.first_name.titleize %> <%= actor.last_name.titleize %></h4>
                        </li>
                      <% end %>
                      </ul>
                    </div>
                  </div>
                  <div class="card-footer">
                    <p>posté par <em class="user-post"><%= actor.user.username %></em></p>
                  </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
           <h1> Allez poster votre premier film!</h1>
           <p><%= link_to '=> par içi', movies_path %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/actors/show.html.erb
<div class="wrapper-actor-info">
  <div class="container">
    <div class="row">
      <div id="actor-div">
        <div class="col-xs-12 col-md-6">
          <div id="display">
            <%= div_for(@actor, class: "foo") do |actor| %>
            <div class="actors-infos">
              <h3><%= actor.first_name.titleize %> <%= actor.last_name.titleize %></h3>
              <p><strong><%= actor.profession.titleize %></strong></p>
              <p><%= actor.biography %></p>
              <p><%= pluralize @reviews.size, "commentaire" %></p>
            </div>

            <div class="partial-reviews">
              <% if @reviews.blank? %>

                <p>Soyez la première personne à poster un commentaire sur <strong><%= actor.first_name %> <%= actor.last_name %></strong></p>

              <% else %>

                <%= render partial: 'reviews/reviews_partial' %>

              <% end %>

              <div id="new-review">

                <%= render partial: "reviews/form", locals: {reviewable: actor} %>

              </div>
            </div>

            <% end %>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="actor-profile">
            <div class="picture" id="image-actor">
              <%= cl_image_tag @actor.image_id, height: 400, width: 400, crop: :fill, class: "image-movie" %>
              </div>
              <p>Filmographie:</p>
              <% @actor.movies.each do |actor_movies| %>
                <div class="actor_movies">
                  <%= cl_image_tag actor_movies.picture, height: 90, width: 70, crop: :fill %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miewer</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/movies/index.html.erb
<% if @movies.blank? == false %>
  <div class="wrapper-cards">
    <div class="container">
      <div class="row">
        <% @movies.each_with_index do |movie, index| %>
          <div class="col-xs-12 col-sm-6 col-md-3">
            <%= link_to movie_path(movie) do %>
              <div class="card" id="movie_<%= index + 1 %>" style="background-image:url('<%= movie.picture? ? cloudinary_url(movie.picture, height: 300, width: 400, crop: :fill, gravity: :face) : image_path('background.jpg') %>');">
                  <div class="card-category"><%= movie.category %></div>
                  <% if movie.available? %>
                  <div class="movie-available">En salle actuellement</div>
                  <% end %>
                    <div class="card-description">
                      <h3><%= movie.title.titleize %></h3>
                    </div>
                </div>
                <% if movie.user == current_user %>
                <div data-movie-id="<%= movie.id %>">
                  <%= link_to movie, method: :delete, data: {confirm: "Are you sure?"} do %>
                    <%= image_tag 'bin-movie.png', class: "bin" %>
                  <% end %>
                </div>
                <% end %>
               <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
<% else %>
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-12 col-md-offset-3">
    <h1>Postez votre "first movie"!</h1>
      <p>Vous êtes désormais administrateur de Miewer, Bravo!</p>
      <p>Votre mission, si toutefois vous l'acceptez, est de poster un bon film avec son acteur principal.</p>
      <p>N'oubliez pas la photo</p>
      <p>Bon courage...</p>
    <div class="button-modal-no-movies-yet">
      <h2><button type="button" class="btn-modal" data-toggle="modal" data-target="#myModal">Post a film</button></h2>
    </div>
  </div>
<% end %>



<%= render "shared/modal" %>

app/views/movies/show.html.erb
<div class="wrapper-movie">
  <div class="container">
    <div class="row">
      <div id="movie-id">
        <div class="col-xs-12 col-md-6">
          <div class="display">
            <%= div_for(@movie, class: "foo") do |movie|%>
              <h3><strong><%= movie.title.titleize %></strong></h3>
              <p><%= movie.description %></p>
              <p>Posté par <strong><%= movie.user.username %></strong> - <em><%= time_ago_in_words(movie.created_at) %></em></p>

              <div class="partial-reviews">
                <% if @reviews.blank? %>

                  <p>Soyez la première personne à poster un commentaire sur <strong><%= movie.title %></strong></p>

                <% else %>

                <%= render partial: 'reviews/reviews_partial' %>

                <% end %>

              <div id="new-review">

                <%= render partial: "reviews/form", locals: {reviewable: movie} %>

              </div>
             </div>

            <% end %>
          </div>
        </div>
        <div class="xs-12 col-md-6">
          <div class="picture">
            <%= cl_image_tag @movie.picture, height: 525, width: 400, crop: :fill, class: "image-movie" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-banner">
  <div class="banner" style="background-image: url(<%= image_path "background.jpg" %>);">
    <div class="banner-content">
      <h1 class="animated fadeInUp">Stay easy</h1>
      <div class="btn-home animated fadeInDown">
        <p><%= link_to "Play",movies_path, class: "btn-medium"  %></p>
      </div>
      </div>
    </div>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [reviewable, Review.new], remote: true do |f|%>
 <p><%= f.input_field :body, class: "form-control" %></p><br>
 <p><%= f.submit class: "btn btn-warning" %></p>
<% end %>

app/views/reviews/_reviews.html.erb
<p>"<%= reviewable.body %>"</p>

app/views/reviews/_reviews_partial.html.erb
<div id="reviews">
    <% @reviews.each do |review| %>
     <%= render partial: "reviews/reviews", locals: {reviewable: review} %>
    <% end %>
</div>

app/views/reviews/create.js.erb
var new_review = $("<%= j render partial: "reviews/reviews", locals: {reviewable: @review} %>").hide();

$('#reviews').append(new_review);

new_review.slideDown();

$('#new-review').find('#review_body').val("");

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Postez un bon film et un acteur!</h4>
      </div>
      <div class="modal-body">
          <%= simple_form_for @movie do |f| %>
            <div class="form-group">
              <%= f.input :title %>
              <%= f.input :description %>
              <%= f.input :date, start_year: Date.today.year - 90,
                              end_year: Date.today.year, discard_day: true,order: [:month, :year] %>
              <%= f.label :category %>
              <%= f.select :category, [ 'Action', 'Horreur', 'Dramatique', 'Comédie', 'Documentaire' ], prompt: "Sélectionnez"  %>
              <%= f.input :picture %>
              <%= f.input :picture_cache, as: :hidden %>
              <%= f.input :available, as: :boolean, checked_value: true, unchecked_value: false, inline_label: 'en salle actuellement?' %>
            </div>

            <%= f.fields_for :actors do |p| %>
              <div class="form-inline">
                <p><strong>Avec quel acteur?</strong></p>
                <%= p.text_area :first_name, placeholder: "prénom", class: "form-control actor-name" %>
                <%= p.text_area :last_name, placeholder: "Nom", row: 10, class: "form-control actor-name"%>
                <%= p.file_field :image_id %>
                <%= p.hidden_field :image_id_cache %>
              </div>
            <% end %>
      </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit 'Enregistrer', class: "btn btn-success" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? && (params[:controller]) == "movies" && params[:action] == "index" %>
  <%= render "shared/navbar_components/navbar_movies_index" %>
<% else %>
  <%= render "shared/navbar_components/navbar" %>
<% end %>

app/views/shared/navbar_components/_navbar.html.erb
<div class="navbar-wagon">

  <% if user_signed_in? %>
    <%= link_to movies_path, class: "navbar-logo-brand" do  %>
      <%= image_tag 'logo.png' %>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-logo-brand" do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
    <div class="navbar-wagon-search">
      <%= link_to actors_path do  %>
        <%= image_tag "actors.png", class: "navbar-wagon-brand", data: { content: "Acteurs" } %>
      <% end %>

      <%= link_to movies_path do %>
        <%= image_tag "movies.png", class: "navbar-wagon-brand", data: { content: "Films" } %>
      <% end %>
    </div>

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "unknown_user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Acteurs",actors_path  %></li>
        <li><%= link_to "Films",movies_path  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/navbar_components/_navbar_movies_index.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to movies_path, id: "logo-brand" do  %>
      <%= image_tag 'logo.png' %>
    <% end %>
  <% else %>
    <%= link_to root_path, id: "logo-brand" do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  <% end %>

  <div class="navbar-right hidden-xs hidden-sm">


    <% if user_signed_in? %>

      <%= link_to actors_path do  %>
        <%= image_tag "actors.png", class: "navbar-movies-brand", data: { content: "Acteurs" } %>
      <% end %>

      <%= link_to movies_path do %>
        <%= image_tag "movies.png", class: "navbar-movies-brand", data: { content: "Films" } %>
      <% end %>
      <div class="navbar-item">
        <div class="dropdown">
          <%= image_tag "unknown_user.png", class: "avatar dropdown-toggle", id: "navbar-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <button type="button" class="btn-modal" data-toggle="modal" data-target="#myModal">Post a film</button>
  </div>

    <% else %>


      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-item navbar-link" %>

    <% end %>

      <div class="navbar-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
            <li><%= link_to "Acteurs",actors_path  %></li>
            <li><%= link_to "Films",movies_path  %></li>
          </ul>
        </div>
      </div>
  </div>
</div>